# Generated by Django 2.2.7 on 2019-11-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('date_pub', models.DateField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
