# Generated by Django 2.2.7 on 2019-11-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizApp', '0002_auto_20191120_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
