# Generated by Django 2.2.7 on 2019-11-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizApp', '0003_auto_20191120_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='date_pub',
        ),
    ]
